// Rendering a capture, and the index over all of them.

// Transcript timestamps are UTC; commits and the developer are not. Everything renders local so a session is dated
// the day it actually happened.
const LOCAL = new Intl.DateTimeFormat("sv-SE", {
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit",
  hour12: false,
});

export const local = (iso) => (iso ? LOCAL.format(new Date(iso)) : "");
export const stamp = (iso) => local(iso).slice(0, 16);
export const day = (iso) => local(iso).slice(0, 10);

/**
 * Both sides are fenced verbatim. Replies are markdown and would otherwise inject their own headings, lists and code
 * blocks into the document; fencing keeps a capture a record rather than a rendering of one.
 */
function fence(text) {
  const longest = Math.max(
    0,
    ...[...text.matchAll(/`+/g)].map((m) => m[0].length),
  );
  const bar = "`".repeat(Math.max(3, longest + 1));
  return `${bar}text\n${text}\n${bar}`;
}

const AGENT_LABEL = { claude: "Claude Code", codex: "Codex", cursor: "Cursor" };

export function renderCapture({
  agent,
  id,
  turns,
  title,
  note,
  commits,
  covers,
}) {
  const first = turns[0].at;
  const last = turns.at(-1).at;
  const span =
    day(first) === day(last)
      ? stamp(first)
      : `${stamp(first)} → ${stamp(last)}`;
  const asked = turns.filter((t) => t.role === "user").length;

  const lines = [
    `# ${title ?? `${AGENT_LABEL[agent] ?? agent} session ${id}`}`,
    "",
    `${span} · ${AGENT_LABEL[agent] ?? agent} · ${asked} prompt${asked === 1 ? "" : "s"}, ${turns.length} turns · session \`${id}\``,
    "",
  ];
  // Which transcripts this file accounts for. A merged conversation has no file under the ids it absorbed, so
  // without this the reminder would report them uncaptured forever.
  lines.push(
    `<!-- capture:covers ${(covers ?? [`${agent}-${id}`]).join(" ")} -->`,
    "",
  );
  if (note) lines.push(note, "");
  if (commits?.length) {
    lines.push("Commits in this window:", "");
    for (const [sha, subject] of commits) lines.push(`- \`${sha}\` ${subject}`);
    lines.push("");
  }
  lines.push("---", "");
  for (const turn of turns) {
    lines.push(
      `### ${turn.role === "user" ? "Asked" : "Replied"} · ${stamp(turn.at)}`,
      "",
      fence(turn.text),
      "",
    );
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/** The index is every capture in date order. There is no ranking — see the spec, §4.5. */
export function renderIndex(entries) {
  const lines = [
    "# Captured conversations",
    "",
    "Every agent session recorded against this repository, in date order. Each file holds one conversation —",
    "prompts and replies verbatim, tool calls stripped.",
    "",
    "Generated by the `capture-conversation` skill. Do not edit this file; edit `.agents/capture-sessions.json`",
    "and regenerate.",
    "",
    "| Date | Agent | Session | What it was |",
    "| --- | --- | --- | --- |",
  ];
  for (const e of entries) {
    const label = AGENT_LABEL[e.agent] ?? e.agent;
    const title = e.title ?? `_untitled_`;
    lines.push(
      `| ${e.date} | ${label} | [${title}](${e.file}) | ${e.note ?? ""} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}
