import { z } from "zod";

/**
 * Every API request and response shape, as Zod schemas with the TypeScript types inferred beside
 * them (`XSchema` / `X`): the whole contract of docs/PRD.md §7, restated on 2026-09-12 with no legacy
 * member (docs/specs/api-reference.md §5). `apps/api` validates requests and documents responses with
 * the schemas; `apps/web` imports the types only, so Zod never enters its bundle. `.meta({ id })` names
 * a schema as an OpenAPI component wherever another schema refers to it (a response envelope's own
 * root stays inline); `.describe()` is the text readers see in `/docs`. A schema that carries an id is
 * never re-described where it is used, or the registry would hold two schemas with one id.
 *
 * The API enforces no authorization (PRD §2, §9): every caller receives every shape in full, and only
 * the caller's own relationships (`following`, `unreadCount`, `read`) vary.
 */

/** Unix time in milliseconds, as every timestamp in the API. */
const UnixMs = z.number().int().describe("Unix time, milliseconds");
const Count = z.number().int().nonnegative();
/** A non-empty id; the format is the Registry's check (400 when malformed). */
const Id = z.string().min(1);
/**
 * The position of the last row in a page, opaque and issued by the API. Pass it back as `cursor`
 * for the next page; null means there is none. Never compose one.
 */
const NextCursor = z
  .string()
  .nullable()
  .describe(
    "Pass back as `cursor` for the next page; null when the range is exhausted. Opaque.",
  );

/**
 * Optional free text (`title`, `explanation`, a chat's `title`). Omit the field to mean "not
 * provided"; a present value must be non-blank and is trimmed. Empty, whitespace-only, and null are
 * `INVALID_INPUT` (owner decision 2026-09-08): the API validates and clients normalise, so a blank
 * never silently becomes a default.
 */
const optionalText = (description: string) =>
  z
    .string()
    .trim()
    .min(1, "must be omitted or non-blank")
    .describe(description)
    .optional();

// --- common (PRD §2, §7) --------------------------------------------------------------------------

export const HealthResponseSchema = z
  .object({ service: z.literal("api"), status: z.literal("ok") })
  .meta({ id: "HealthResponse", description: "`GET /health`" });
export type HealthResponse = z.infer<typeof HealthResponseSchema>;

/**
 * The typed error codes and their HTTP statuses. There is no 403: the API enforces no authorization
 * (PRD §9). `apps/api` infers its `DomainErrorCode` from this schema, so the two cannot drift.
 */
export const ErrorCodeSchema = z
  .enum([
    "UNAUTHENTICATED",
    "FORBIDDEN",
    "INVALID_INPUT",
    "NOT_FOUND",
    "INVALID_STATE",
    "UPSTREAM_UNAVAILABLE",
  ])
  .meta({
    id: "ErrorCode",
    description:
      "UNAUTHENTICATED (401: no session, or one the API does not accept), FORBIDDEN (403: a session, but not the owner, on a catalog operation), INVALID_INPUT (400), NOT_FOUND (404), INVALID_STATE (409), UPSTREAM_UNAVAILABLE (502: YouTube did not answer usably).",
  });
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;

export const ErrorResponseSchema = z
  .object({
    error: z
      .string()
      .describe("What went wrong. Typed errors are prefixed with their code."),
    code: ErrorCodeSchema.optional(),
  })
  .meta({
    id: "ErrorResponse",
    description:
      "Every non-2xx response body. `code` is absent only on an unexpected 500.",
  });
export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;

export const UserRoleSchema = z.enum(["owner", "user"]).meta({
  id: "UserRole",
  description:
    "`owner` is the identity the web offers catalog management to; everyone else is `user`. Rendering only: the API enforces no authorization.",
});
export type UserRole = z.infer<typeof UserRoleSchema>;

export const MeResponseSchema = z
  .object({
    userId: z
      .string()
      .describe(
        "The identity's stable id, generated by the Registry. It names the caller's private store and outlives any change of address.",
      ),
    email: z.string().describe("The caller's normalized X-User-Email."),
    role: UserRoleSchema,
  })
  .meta({ id: "MeResponse", description: "`GET /me`" });
export type MeResponse = z.infer<typeof MeResponseSchema>;

// --- enums (PRD §5.3, §7): each mirrors a CHECK constraint or a fixed contract set ---------------

export const ChannelStatusSchema = z
  .enum(["requested", "approved", "declined"])
  .meta({
    id: "ChannelStatus",
    description:
      "The owner's answer about catalog membership. `requested` awaits review; `approved` is discovered and readable; `declined` is hidden from the catalog list, keeps everything, and can be approved or requested again.",
  });
export type ChannelStatus = z.infer<typeof ChannelStatusSchema>;

export const PausedBySchema = z.enum(["owner", "system"]).meta({
  id: "PausedBy",
  description:
    "`system` when no one follows the channel; `owner` when the owner paused it. Pause stops scheduled discovery only.",
});
export type PausedBy = z.infer<typeof PausedBySchema>;

export const EpisodeStatusSchema = z
  .enum(["pending", "available", "failed", "skipped"])
  .meta({
    id: "EpisodeStatus",
    description:
      "`pending` is being processed or recovering; `available` has a verified vector generation and a summary; `failed` is a `publish` window that closed without a summary; `skipped` is deliberate and reversible.",
  });
export type EpisodeStatus = z.infer<typeof EpisodeStatusSchema>;

export const ProcessingIntentSchema = z.enum(["publish", "replace"]).meta({
  id: "ProcessingIntent",
  description:
    "What an episode's open processing window is for: `publish` works toward a pending episode's first summary; `replace` re-processes an available one while its current summary and vectors stay readable.",
});
export type ProcessingIntent = z.infer<typeof ProcessingIntentSchema>;

export const EpisodeFailureCodeSchema = z.enum(["INGESTION_TIMEOUT"]).meta({
  id: "EpisodeFailureCode",
  description:
    "The one episode failure: a publication that did not succeed within its 48-hour window. The latest attempt's reason is in `failureDetail`.",
});
export type EpisodeFailureCode = z.infer<typeof EpisodeFailureCodeSchema>;

export const EpisodeSkipReasonSchema = z
  .enum(["SHORT", "NON_ENGLISH", "UNPLAYABLE", "OWNER"])
  .meta({
    id: "EpisodeSkipReason",
    description:
      "Why an episode was skipped: under three minutes, no English caption track, unplayable, or by the owner by hand (`OWNER`, which names who).",
  });
export type EpisodeSkipReason = z.infer<typeof EpisodeSkipReasonSchema>;

export const EpisodeWaitReasonSchema = z
  .enum(["CAPTIONS", "PROVIDER_LIMIT"])
  .meta({
    id: "EpisodeWaitReason",
    description:
      "Why a pending episode is waiting for a later attempt, derived from its latest attempt: no captions yet, or transcript credits are exhausted.",
  });
export type EpisodeWaitReason = z.infer<typeof EpisodeWaitReasonSchema>;

export const SummaryFormatSchema = z
  .enum(["structured", "raw_fallback"])
  .meta({ id: "SummaryFormat" });
export type SummaryFormat = z.infer<typeof SummaryFormatSchema>;

export const IngestionRunKindSchema = z.enum(["initial", "scheduled"]).meta({
  id: "IngestionRunKind",
  description:
    "`initial` until a run of the channel has created an episode (imports the newest `initialImportCount` entries); `scheduled` afterwards (imports untracked entries published after first approval).",
});
export type IngestionRunKind = z.infer<typeof IngestionRunKindSchema>;

export const FeedStatusSchema = z.enum(["read", "unavailable"]).meta({
  id: "FeedStatus",
  description: "Whether the channel's RSS feed was read on this run.",
});
export type FeedStatus = z.infer<typeof FeedStatusSchema>;

export const AttemptTriggerSchema = z
  .enum(["channel_ingestion", "scheduled_recovery", "owner_retry"])
  .meta({
    id: "AttemptTrigger",
    description:
      "What started the attempt: a discovery run creating the episode, the recovery schedule, or Retry (which names who asked).",
  });
export type AttemptTrigger = z.infer<typeof AttemptTriggerSchema>;

export const AttemptStatusSchema = z
  .enum(["running", "available", "failed", "skipped", "waiting", "blocked"])
  .meta({
    id: "AttemptStatus",
    description:
      "`running` while the Workflow instance is alive; `available` published; `waiting` finished with a recoverable wait; `failed` finished with a technical error (recoverable until the deadline); `skipped` classified the video deterministically; `blocked` was refused by the provider pre-flight and never launched.",
  });
export type AttemptStatus = z.infer<typeof AttemptStatusSchema>;

export const AttemptOutcomeCodeSchema = z
  .enum([
    "CAPTIONS",
    "PROVIDER_LIMIT",
    "SHORT",
    "NON_ENGLISH",
    "UNPLAYABLE",
    "PROVIDER_AUTH",
    "PROVIDER_RATE_LIMIT",
    "PROVIDER_HTTP",
    "PROVIDER_PARSE",
    "TRANSCRIPT_TOO_LARGE",
    "EMBEDDING_FAILED",
    "VECTORIZE_INCOMPLETE",
    "SUMMARY_FAILED",
    "WORKFLOW_LOST",
  ])
  .meta({
    id: "AttemptOutcomeCode",
    description:
      "The attempt's reason, by status: `waiting` → CAPTIONS, PROVIDER_LIMIT; `skipped` → SHORT, NON_ENGLISH, UNPLAYABLE; `blocked` → PROVIDER_AUTH, PROVIDER_LIMIT; `failed` → PROVIDER_AUTH, PROVIDER_RATE_LIMIT, PROVIDER_HTTP, PROVIDER_PARSE, TRANSCRIPT_TOO_LARGE, EMBEDDING_FAILED, VECTORIZE_INCOMPLETE, SUMMARY_FAILED, WORKFLOW_LOST. `running` and `available` attempts carry null.",
  });
export type AttemptOutcomeCode = z.infer<typeof AttemptOutcomeCodeSchema>;

export const TranscriptProviderStatusSchema = z
  .enum(["ok", "auth_failed", "unreachable"])
  .meta({
    id: "TranscriptProviderStatus",
    description:
      "`ok`: the key is accepted and the credit count is current; `auth_failed`: the provider rejected the key; `unreachable`: no key is configured, or the call failed, timed out, or answered unusably.",
  });
export type TranscriptProviderStatus = z.infer<
  typeof TranscriptProviderStatusSchema
>;

export const ChatRoleSchema = z
  .enum(["user", "assistant"])
  .meta({ id: "ChatRole" });
export type ChatRole = z.infer<typeof ChatRoleSchema>;

export const ChatMessageStatusSchema = z
  .enum(["pending", "completed", "failed"])
  .meta({
    id: "ChatMessageStatus",
    description:
      "`pending` while the assistant's reply is being produced; `completed` or `failed` afterwards.",
  });
export type ChatMessageStatus = z.infer<typeof ChatMessageStatusSchema>;

// --- discovery runs (PRD §4.2 rules 1–4) ----------------------------------------------------------

/**
 * One completed RSS feed check of one channel. A run exists only once complete and reports only what
 * the feed check found; the episodes it discovered are those whose `processing.discoveredByRunId`
 * names it, and their processing history is on their attempts.
 */
export const IngestionRunSchema = z
  .object({
    runId: Id,
    channelId: Id,
    kind: IngestionRunKindSchema,
    feedStatus: FeedStatusSchema,
    discoveredCount: Count.describe(
      'Episodes this run created; 0 for "nothing new" and for an unavailable feed.',
    ),
    episodeLimit: z
      .number()
      .int()
      .positive()
      .nullable()
      .describe(
        "The initial run's `initialImportCount`; null for a scheduled run.",
      ),
    startedAt: UnixMs,
    finishedAt: UnixMs,
  })
  .meta({
    id: "IngestionRun",
    description:
      "One completed RSS discovery run of a channel: kind, whether the feed was read, and how many episodes were created. Episode outcomes are not here; each episode names the run that discovered it.",
  });
export type IngestionRun = z.infer<typeof IngestionRunSchema>;

/** `GET /channels/:id/runs` — newest first. */
export const IngestionRunsResponseSchema = z
  .object({ runs: z.array(IngestionRunSchema) })
  .meta({
    id: "IngestionRunsResponse",
    description: "`GET /channels/:id/runs` — newest first.",
  });
export type IngestionRunsResponse = z.infer<typeof IngestionRunsResponseSchema>;

/** `POST /channels/:id/runs` (M3) — the discovery run just performed. */
export const IngestionRunResponseSchema = z
  .object({ run: IngestionRunSchema })
  .meta({
    id: "IngestionRunResponse",
    description:
      "`POST /channels/:id/runs` — the completed discovery run, including one that found nothing new.",
  });
export type IngestionRunResponse = z.infer<typeof IngestionRunResponseSchema>;

// --- channels (PRD §4.1, §4.3, §7) ----------------------------------------------------------------

export const EpisodeCountsSchema = z
  .object({
    available: Count,
    pending: Count,
    failed: Count,
    skipped: Count,
  })
  .meta({
    id: "EpisodeCounts",
    description:
      "Episodes by status. The four add up to every tracked episode; there is no `waiting` count, the reason a pending episode is not summarised yet is on its row.",
  });
export type EpisodeCounts = z.infer<typeof EpisodeCountsSchema>;

/** The management facts of a channel, present for every caller; the web shows them on the Owner screens. */
export const ChannelManagementSchema = z
  .object({
    initialImportCount: z
      .number()
      .int()
      .positive()
      .describe("How many of the newest feed entries the initial run imports."),
    reviewedByEmail: z
      .string()
      .nullable()
      .describe("Who approved or declined last; any identity may."),
    pausedBy: PausedBySchema.nullable(),
    pausedAt: UnixMs.nullable(),
    lastCheckedAt: UnixMs.nullable().describe(
      "When the feed was last read successfully; an unavailable read does not move it.",
    ),
    latestRun: IngestionRunSchema.nullable().describe(
      "The newest completed discovery run, or null before the first.",
    ),
    neverStarted: z
      .boolean()
      .describe("Approved, yet no discovery run has ever been recorded."),
    createdAt: UnixMs,
    updatedAt: UnixMs,
  })
  .meta({
    id: "ChannelManagement",
    description:
      "The management facts of a channel, present for every caller: the API enforces no authorization, and the web shows them on the Owner screens.",
  });
export type ChannelManagement = z.infer<typeof ChannelManagementSchema>;

/**
 * A catalog channel as every caller sees it, `management` included. Only `following` depends on
 * who is asking.
 */
export const ChannelSchema = z
  .object({
    channelId: Id.describe("Canonical `UC…` id."),
    title: z.string(),
    canonicalUrl: z.string(),
    status: ChannelStatusSchema,
    paused: z
      .boolean()
      .describe("No scheduled discovery while true. Approved channels only."),
    approvedAt: UnixMs.nullable().describe(
      'First approval; never reset. A declined channel with a value reads "Withdrawn".',
    ),
    reviewedAt: UnixMs.nullable(),
    reviewNote: z
      .string()
      .nullable()
      .describe(
        "The owner's latest note, shown to followers of a declined channel.",
      ),
    lastIngestedAt: UnixMs.nullable().describe(
      "The newest first availability among the channel's episodes; derived, never stored.",
    ),
    episodes: EpisodeCountsSchema,
    following: z.boolean().describe("Whether the caller follows this channel."),
    followerCount: Count.describe(
      "Active followers, from the Registry's follower record.",
    ),
    management: ChannelManagementSchema,
  })
  .meta({
    id: "Channel",
    description:
      "A catalog channel as every caller sees it, `management` included. Only `following` depends on who is asking.",
  });
export type Channel = z.infer<typeof ChannelSchema>;

/** `GET /channels` — requested and approved channels; `?scope=all` adds declined ones. */
export const ChannelsResponseSchema = z
  .object({ channels: z.array(ChannelSchema) })
  .meta({
    id: "ChannelsResponse",
    description:
      "`GET /channels` — requested and approved channels; `?scope=all` adds declined ones.",
  });
export type ChannelsResponse = z.infer<typeof ChannelsResponseSchema>;

/** `GET /channels/:id`, `POST /channels`, and the channel actions. */
export const ChannelResponseSchema = z.object({ channel: ChannelSchema }).meta({
  id: "ChannelResponse",
  description:
    "`GET /channels/:id`, `POST /channels`, and the channel actions.",
});
export type ChannelResponse = z.infer<typeof ChannelResponseSchema>;

/** `POST /channels` — a bare `UC…` id or a URL containing `/channel/UC…`; the feed title is used unless given. */
export const CreateChannelBodySchema = z
  .object({
    channelId: z
      .string()
      .trim()
      .min(1)
      .describe("A bare `UC…` id or any URL containing `/channel/UC…`."),
    title: optionalText(
      "Overrides the title read from the channel's RSS feed. Honoured from any caller; the web offers it to the owner.",
    ),
    initialImportCount: z
      .number()
      .int()
      .positive()
      .describe(
        "Recent episodes to import first; defaults to five. Honoured from any caller; the web offers it to the owner.",
      )
      .optional(),
  })
  .meta({
    id: "CreateChannelBody",
    description:
      "`POST /channels` — a bare `UC…` id or a URL containing `/channel/UC…`; the feed title is used unless given.",
  });
export type CreateChannelBody = z.infer<typeof CreateChannelBodySchema>;

/** `POST /channels/:id/approve` — every field optional. */
export const ApproveChannelBodySchema = z
  .object({
    title: optionalText("Overrides the channel's title."),
    initialImportCount: z
      .number()
      .int()
      .positive()
      .describe("Recent episodes to import first; defaults to five.")
      .optional(),
    explanation: optionalText("Shown to the channel's followers."),
  })
  .meta({
    id: "ApproveChannelBody",
    description: "`POST /channels/:id/approve` — every field optional.",
  });
export type ApproveChannelBody = z.infer<typeof ApproveChannelBodySchema>;

/** `POST /channels/:id/decline` */
export const DeclineChannelBodySchema = z
  .object({
    explanation: optionalText(
      "Shown to the channel's followers with the word Declined or Withdrawn.",
    ),
  })
  .meta({
    id: "DeclineChannelBody",
    description: "`POST /channels/:id/decline`",
  });
export type DeclineChannelBody = z.infer<typeof DeclineChannelBodySchema>;

/** 409 body when the channel is declined: the client shows the note and offers Request again. */
export const ChannelDeclinedResponseSchema = z
  .object({
    error: z.string(),
    code: z.literal("INVALID_STATE"),
    channelId: Id,
    status: z.literal("declined"),
    reviewNote: z.string().nullable(),
    reviewedAt: UnixMs.nullable(),
  })
  .meta({
    id: "ChannelDeclinedResponse",
    description:
      "409 body for `POST /channels` and `PUT /follows/:channelId` when the channel is declined; the client shows the note and offers Request again.",
  });
export type ChannelDeclinedResponse = z.infer<
  typeof ChannelDeclinedResponseSchema
>;

// --- episodes, attempts, and the digest (PRD §4.2, §4.4, §7) -------------------------------------

export const TakeawaySchema = z
  .object({
    text: z.string(),
    startSec: z
      .number()
      .nonnegative()
      .nullable()
      .describe(
        "The moment the takeaway comes from, for a `https://youtu.be/<episodeId>?t=<startSec>` link; null when the model gave no usable marker.",
      ),
  })
  .meta({
    id: "Takeaway",
    description: "One takeaway with the moment it comes from.",
  });
export type Takeaway = z.infer<typeof TakeawaySchema>;

export const EpisodeSummarySchema = z
  .discriminatedUnion("format", [
    z.object({
      format: z.literal("structured"),
      executiveSummary: z.string(),
      takeaways: z.array(TakeawaySchema),
      topicTags: z.array(z.string()),
    }),
    z.object({
      format: z.literal("raw_fallback"),
      rawText: z.string(),
    }),
  ])
  .meta({
    id: "EpisodeSummary",
    description:
      "The shared per-episode summary: structured when the model returned valid JSON (after one retry), otherwise the raw text it produced.",
  });
export type EpisodeSummary = z.infer<typeof EpisodeSummarySchema>;

export const RelatedEpisodeSchema = z
  .object({ episodeId: Id, title: z.string() })
  .meta({
    id: "RelatedEpisode",
    description:
      "Another available episode whose transcript is close to this one, already filtered to the caller's eligible channels.",
  });
export type RelatedEpisode = z.infer<typeof RelatedEpisodeSchema>;

/** One execution of an episode: one Workflow instance, or one start that pre-flight blocked. */
export const EpisodeIngestionAttemptSchema = z
  .object({
    attemptId: Id,
    episodeId: Id,
    trigger: AttemptTriggerSchema,
    requestedByEmail: z
      .string()
      .nullable()
      .describe("Who asked; set exactly for `owner_retry`."),
    intent: ProcessingIntentSchema,
    status: AttemptStatusSchema,
    outcomeCode: AttemptOutcomeCodeSchema.nullable(),
    failureDetail: z.string().nullable(),
    workflowId: z
      .string()
      .nullable()
      .describe(
        "The Workflow instance; null for a `blocked` attempt, which never launched.",
      ),
    stagedChunkCount: Count.nullable().describe(
      "How many vectors this attempt staged, set when embedding began.",
    ),
    startedAt: UnixMs,
    finishedAt: UnixMs.nullable().describe("Null only while `running`."),
  })
  .meta({
    id: "EpisodeIngestionAttempt",
    description:
      "One execution of an episode: first processing, scheduled recovery, or Retry. Where an episode's reason lives.",
  });
export type EpisodeIngestionAttempt = z.infer<
  typeof EpisodeIngestionAttemptSchema
>;

/** Processing detail of an episode, present for every caller; the web shows it on the Owner screens. */
export const EpisodeProcessingSchema = z
  .object({
    discoveredByRunId: Id.describe(
      "The discovery run that created the episode; immutable.",
    ),
    intent: ProcessingIntentSchema.nullable().describe(
      "Set, with the three window timestamps, while a processing window is open. The window opens when the episode is created, not after a failure.",
    ),
    windowStartedAt: UnixMs.nullable(),
    windowDeadlineAt: UnixMs.nullable().describe(
      "48 hours after the window opened.",
    ),
    nextAttemptAt: UnixMs.nullable(),
    attemptCount: Count.describe(
      "Attempts that launched since the window last opened; a blocked start never counts. Diagnostic only.",
    ),
    latestAttempt: EpisodeIngestionAttemptSchema.nullable().describe(
      "Where the reason lives; null before the first start.",
    ),
    failureCode: EpisodeFailureCodeSchema.nullable().describe(
      "Written once, at the timeout, with the latest attempt's reason in `failureDetail`.",
    ),
    failureDetail: z.string().nullable(),
    skippedAt: UnixMs.nullable(),
    skippedByEmail: z
      .string()
      .nullable()
      .describe("Set exactly for an `OWNER` skip."),
    transcriptCheckedAt: UnixMs.nullable(),
    durationSec: Count.nullable().describe(
      "The episode's runtime, as the transcript provider reported it; null before a transcript was fetched.",
    ),
    chunkCount: Count.nullable(),
    vectorizedAt: UnixMs.nullable(),
    createdAt: UnixMs,
    updatedAt: UnixMs,
  })
  .meta({
    id: "EpisodeProcessing",
    description:
      "Processing detail of an episode, present for every caller; the web shows it on the Owner screens.",
  });
export type EpisodeProcessing = z.infer<typeof EpisodeProcessingSchema>;

/**
 * An episode of a catalog channel, the same for every caller: summary, related titles (filtered to
 * the caller's eligible channels), and `processing`. `read` accompanies a summary returned to an
 * eligible caller and describes the row, not the request: reading never records a receipt
 * (docs/PRD.md §4.4), so only `POST …/read` changes it.
 */
export const EpisodeSchema = z
  .object({
    episodeId: Id,
    channelId: Id,
    channelTitle: z.string(),
    title: z.string(),
    publishedAt: UnixMs,
    status: EpisodeStatusSchema,
    skipReason: EpisodeSkipReasonSchema.nullable().describe(
      "Why there is no summary, when the episode was skipped.",
    ),
    waitReason: EpisodeWaitReasonSchema.nullable().describe(
      "Why a pending episode is not summarised yet, from its latest attempt; null otherwise.",
    ),
    summaryAvailableAt: UnixMs.nullable().describe(
      "When the summary first became available; never reset. The digest's window and order.",
    ),
    summary: EpisodeSummarySchema.nullable(),
    related: z
      .array(RelatedEpisodeSchema)
      .describe("Already filtered to the caller's eligible channels."),
    read: z
      .boolean()
      .describe(
        "For an eligible caller (active follower of an approved channel) with a returned summary: whether they have a read receipt for it. Absent for everyone else. No read route writes one; `POST /channels/{id}/episodes/{episodeId}/read` does.",
      )
      .optional(),
    processing: EpisodeProcessingSchema,
  })
  .meta({
    id: "Episode",
    description:
      "An episode of a catalog channel, the same for every caller: summary, related titles filtered to the caller's eligible channels, and `processing`. `read` accompanies a summary returned to an eligible caller.",
  });
export type Episode = z.infer<typeof EpisodeSchema>;

/** `GET /channels/:id/episodes?limit=` — newest first, with summaries and processing detail for every caller. */
export const EpisodesResponseSchema = z
  .object({ episodes: z.array(EpisodeSchema) })
  .meta({
    id: "EpisodesResponse",
    description:
      "`GET /channels/:id/episodes?limit=` — newest first, with summaries and processing detail for every caller.",
  });
export type EpisodesResponse = z.infer<typeof EpisodesResponseSchema>;

/** One episode: the single-episode read, the two read-receipt writes, and skip. */
export const EpisodeResponseSchema = z.object({ episode: EpisodeSchema }).meta({
  id: "EpisodeResponse",
  description:
    "`GET /channels/:id/episodes/:episodeId`, `POST` and `DELETE /channels/:id/episodes/:episodeId/read`, `POST /channels/:id/episodes/:episodeId/skip`",
});
export type EpisodeResponse = z.infer<typeof EpisodeResponseSchema>;

/** `POST /channels/:id/episodes/:episodeId/retry` (M3) — the episode and the attempt just started, or blocked. */
export const EpisodeRetryResponseSchema = z
  .object({
    episode: EpisodeSchema,
    attempt: EpisodeIngestionAttemptSchema.describe(
      "`running` when work started, `blocked` when the provider pre-flight refused it.",
    ),
  })
  .meta({
    id: "EpisodeRetryResponse",
    description:
      "`POST /channels/:id/episodes/:episodeId/retry` — the episode and the attempt just started, or blocked.",
  });
export type EpisodeRetryResponse = z.infer<typeof EpisodeRetryResponseSchema>;

/**
 * What YouTube's two feeds say about a channel id, read on demand and stored nowhere: the middle of
 * the three steps that add a channel (docs/specs/design-phase.md §4.6). The counts are what tell a
 * reader whether this channel will actually produce episodes — discovery reads the long-form feed
 * alone, so a channel whose newest fifteen are all Shorts makes none.
 */
export const ChannelFeedSchema = z
  .object({
    channelId: Id.describe(
      "Canonical `UC…` id, extracted from what was pasted.",
    ),
    title: z.string().describe("The channel's name, as its feed gives it."),
    entryCount: Count.describe(
      "How many uploads the channel feed carried, at most fifteen.",
    ),
    longFormCount: Count.describe(
      "How many of those are long-form, and so could become episodes. Shorts and live streams are the rest.",
    ),
    newestLongFormAt: UnixMs.nullable().describe(
      "When the newest long-form upload was published; null when there are none.",
    ),
  })
  .meta({
    id: "ChannelFeed",
    description:
      "What YouTube's channel and long-form feeds say about an id right now. Read on demand; nothing is stored.",
  });
export type ChannelFeed = z.infer<typeof ChannelFeedSchema>;

/** `GET /channels/feed?channelId=` — the reading, and whatever the catalog already holds for it. */
export const ChannelFeedResponseSchema = z
  .object({
    feed: ChannelFeedSchema,
    channel: ChannelSchema.nullable().describe(
      "The catalog's channel when it already holds this id, so the last step knows whether it is adding, following, or looking at a declined one; null otherwise.",
    ),
  })
  .meta({
    id: "ChannelFeedResponse",
    description:
      "`GET /channels/feed?channelId=` — what the feeds say, and what the catalog already holds.",
  });
export type ChannelFeedResponse = z.infer<typeof ChannelFeedResponseSchema>;

/**
 * One row of a compact digest: what the calendar needs to count a day and the channel filter needs
 * to attribute it, and nothing else. `summaryAvailableAt` is the day the summary belongs to, which
 * never moves (docs/PRD.md §4.4).
 */
export const DigestRowSchema = z
  .object({
    episodeId: Id,
    channelId: Id,
    summaryAvailableAt: UnixMs.describe(
      "When the summary first became available; the day it belongs to, permanently.",
    ),
    read: z.boolean().describe("Whether the caller has a read receipt for it."),
  })
  .meta({
    id: "DigestRow",
    description:
      "One row of a compact digest: enough to count a day and attribute it to a channel, without the summary body.",
  });
export type DigestRow = z.infer<typeof DigestRowSchema>;

/** `GET /digest` — a page of full episodes, newest availability first. */
export const DigestEpisodesResponseSchema = z
  .object({
    compact: z.literal(false),
    episodes: z.array(EpisodeSchema),
    nextCursor: NextCursor,
  })
  .meta({
    id: "DigestEpisodesResponse",
    description:
      "`GET /digest` — a page of episodes with their summaries, newest availability first.",
  });
export type DigestEpisodesResponse = z.infer<
  typeof DigestEpisodesResponseSchema
>;

/** `GET /digest?compact=true` — the same page as rows, for the calendar. */
export const DigestRowsResponseSchema = z
  .object({
    compact: z.literal(true),
    rows: z.array(DigestRowSchema),
    nextCursor: NextCursor,
  })
  .meta({
    id: "DigestRowsResponse",
    description:
      "`GET /digest?compact=true` — the same page as rows, so five weeks of calendar cost one small response.",
  });
export type DigestRowsResponse = z.infer<typeof DigestRowsResponseSchema>;

/**
 * `GET /digest` — the one route behind Queue, History and the calendar: eligible summaries in a
 * range, newest availability first, paged by cursor. `compact` says which body came back; it is
 * echoed so a client can narrow the union without remembering what it asked for.
 */
export const DigestResponseSchema = z
  .discriminatedUnion("compact", [
    DigestEpisodesResponseSchema,
    DigestRowsResponseSchema,
  ])
  .meta({
    id: "DigestResponse",
    description:
      "`GET /digest` — eligible summaries in a range, newest availability first; `compact` selects between full episodes and rows.",
  });
export type DigestResponse = z.infer<typeof DigestResponseSchema>;

// --- follows and followers (PRD §4.3) -------------------------------------------------------------

/** One of the caller's follows, with its channel embedded. */
export const FollowSchema = z
  .object({
    channelId: Id,
    followedAt: UnixMs,
    unfollowedAt: UnixMs.nullable().describe(
      "Set on unfollow and retained as a tombstone; null while the follow is active.",
    ),
    channel: ChannelSchema,
    unreadCount: Count.describe(
      "Available episodes the caller has no read receipt for; 0 unless the channel is approved.",
    ),
  })
  .meta({
    id: "Follow",
    description:
      "One of the caller's follows, with its channel embedded. A follow of a declined channel stays listed; the follow row is never removed.",
  });
export type Follow = z.infer<typeof FollowSchema>;

/** `GET /follows` — active follows, most recent ingestion first. */
export const FollowsResponseSchema = z
  .object({ follows: z.array(FollowSchema) })
  .meta({
    id: "FollowsResponse",
    description:
      "`GET /follows` — active follows, most recent ingestion first.",
  });
export type FollowsResponse = z.infer<typeof FollowsResponseSchema>;

/** `PUT /follows/:channelId`, `DELETE /follows/:channelId` */
export const FollowResponseSchema = z.object({ follow: FollowSchema }).meta({
  id: "FollowResponse",
  description: "`PUT /follows/:channelId`, `DELETE /follows/:channelId`",
});
export type FollowResponse = z.infer<typeof FollowResponseSchema>;

export const FollowerSchema = z
  .object({
    userId: z.string().describe("The follower's stable identity id."),
    email: z
      .string()
      .describe(
        "The follower's address, resolved from their id when the list is built rather than stored on the follow.",
      ),
    followedAt: UnixMs,
  })
  .meta({
    id: "Follower",
    description: "One active follower of a channel.",
  });
export type Follower = z.infer<typeof FollowerSchema>;

/** `GET /channels/:id/followers` — active followers, oldest first. */
export const FollowersResponseSchema = z
  .object({ followers: z.array(FollowerSchema) })
  .meta({
    id: "FollowersResponse",
    description:
      "`GET /channels/:id/followers` — active followers, oldest first.",
  });
export type FollowersResponse = z.infer<typeof FollowersResponseSchema>;

// --- the session handoff (docs/specs/auth-phase.md §4.5) ----------------------------------------

export const SessionStartQuerySchema = z
  .object({
    provider: z
      .string()
      .describe("A configured social provider, e.g. `google`."),
    next: z
      .string()
      .describe(
        "Where to return the reader after sign-in. Must be inside an origin `WEB_ORIGINS` allows, or the request is refused and nothing is minted.",
      ),
  })
  .meta({ id: "SessionStartQuery", description: "`GET /session/start`" });

export const SessionExchangeBodySchema = z
  .object({
    code: z
      .string()
      .min(1)
      .describe("The single-use code the callback put in the URL fragment."),
  })
  .meta({ id: "SessionExchangeBody", description: "`POST /session/exchange`" });
export type SessionExchangeBody = z.infer<typeof SessionExchangeBodySchema>;

export const SessionExchangeResponseSchema = z
  .object({
    token: z
      .string()
      .describe(
        "The session token, to be sent as `Authorization: Bearer`. Returned in this body and nowhere else: it never enters a URL, a redirect, or browser history.",
      ),
    expiresAt: UnixMs.describe("When the session stops being accepted."),
    userId: z.string().describe("better-auth's user id for this session."),
    email: z
      .string()
      .nullable()
      .describe(
        "The address on the account, or null for a provider that returned none.",
      ),
  })
  .meta({
    id: "SessionExchangeResponse",
    description: "`POST /session/exchange` — the session, once, for a code.",
  });
export type SessionExchangeResponse = z.infer<
  typeof SessionExchangeResponseSchema
>;

// --- catalog (PRD §7 `GET /catalog`) --------------------------------------------------------------

/** The transcript provider's health, from its status endpoint, cached for five minutes per isolate. */
export const TranscriptProviderHealthSchema = z
  .object({
    remainingCredits: Count.nullable().describe(
      "Credits left this month; null unless `status` is `ok`.",
    ),
    status: TranscriptProviderStatusSchema,
  })
  .meta({
    id: "TranscriptProviderHealth",
    description:
      "The transcript provider's health, from its status endpoint, cached for five minutes. The catalog never fails because of it.",
  });
export type TranscriptProviderHealth = z.infer<
  typeof TranscriptProviderHealthSchema
>;

/** The catalog's aggregate state, for the attention card and health strip. */
export const CatalogSchema = z
  .object({
    channels: z.object({
      requested: Count,
      approved: Count.describe("Approved and not paused."),
      paused: Count.describe(
        "Approved and paused, by the owner or the system.",
      ),
      declined: Count,
    }),
    episodes: EpisodeCountsSchema,
    attention: z.object({
      failedEpisodes: Count.describe(
        "Publications that exhausted their 48-hour window, in approved channels: a declined channel's episodes keep recovering but are not the owner's work.",
      ),
      neverStarted: Count.describe(
        "Approved channels with no discovery run row at all.",
      ),
      requested: Count.describe("Channels awaiting review."),
    }),
    lastSuccessfulIngestionAt: UnixMs.nullable().describe(
      "The newest first availability anywhere in the catalog; derived, never stored.",
    ),
    transcripts: TranscriptProviderHealthSchema,
  })
  .meta({ id: "Catalog", description: "The catalog's aggregate state." });
export type Catalog = z.infer<typeof CatalogSchema>;

/** `GET /catalog` */
export const CatalogResponseSchema = z
  .object({ catalog: CatalogSchema })
  .meta({ id: "CatalogResponse", description: "`GET /catalog`" });
export type CatalogResponse = z.infer<typeof CatalogResponseSchema>;

// --- chats and preferences (PRD §4.5, §7; M4 registers the routes) --------------------------------
// Written now so the M4 routes confirm these rather than redesign them (docs/specs/api-reference.md
// §5.9). They mirror the User DO's stored records. Unreferenced by any route until M4, so absent from
// the document until then.

export const ChatSchema = z
  .object({
    chatId: Id,
    title: z.string().nullable(),
    createdAt: UnixMs,
    updatedAt: UnixMs.describe("Moves when a message is added."),
  })
  .meta({
    id: "Chat",
    description:
      "One of the caller's independent conversations. Every chat searches all channels the caller currently follows that are approved.",
  });
export type Chat = z.infer<typeof ChatSchema>;

export const ChatSourceSchema = z
  .object({
    position: Count,
    episodeId: Id,
    channelId: Id,
    episodeTitle: z.string(),
    channelTitle: z.string(),
    startSec: z
      .number()
      .nonnegative()
      .describe("Link: `https://youtu.be/<episodeId>?t=<startSec>`."),
  })
  .meta({
    id: "ChatSource",
    description:
      "A citation snapshot taken when the reply was produced; later catalog changes never rewrite it.",
  });
export type ChatSource = z.infer<typeof ChatSourceSchema>;

export const ChatMessageSchema = z
  .object({
    messageId: Id,
    chatId: Id,
    sequenceNumber: Count,
    role: ChatRoleSchema,
    content: z.string().describe("Empty while an assistant reply is pending."),
    status: ChatMessageStatusSchema,
    failureCode: z.string().nullable(),
    replyToMessageId: Id.nullable().describe("Set on every assistant message."),
    aboutEpisodeId: Id.nullable().describe(
      "The episode this question was scoped to, or null for a global one. Set on the question, never on the reply.",
    ),
    promptVersion: z
      .string()
      .nullable()
      .describe(
        "The chat prompt that produced this reply; null on a question.",
      ),
    truncated: z
      .boolean()
      .nullable()
      .describe(
        "Whether this reply hit the model's output cap and was trimmed to its last complete sentence; null on a question.",
      ),
    sources: z.array(ChatSourceSchema),
    createdAt: UnixMs,
    updatedAt: UnixMs,
  })
  .meta({ id: "ChatMessage", description: "One message in a chat." });
export type ChatMessage = z.infer<typeof ChatMessageSchema>;

/** `GET /chats` — most recently updated first. */
export const ChatsResponseSchema = z
  .object({ chats: z.array(ChatSchema) })
  .meta({
    id: "ChatsResponse",
    description: "`GET /chats` — most recently updated first.",
  });
export type ChatsResponse = z.infer<typeof ChatsResponseSchema>;

/** `POST /chats` */
export const ChatResponseSchema = z
  .object({ chat: ChatSchema })
  .meta({ id: "ChatResponse", description: "`POST /chats`" });
export type ChatResponse = z.infer<typeof ChatResponseSchema>;

/** `GET /chats/:id/messages?limit=` — ascending sequence. */
export const ChatMessagesResponseSchema = z
  .object({ chat: ChatSchema, messages: z.array(ChatMessageSchema) })
  .meta({
    id: "ChatMessagesResponse",
    description: "`GET /chats/:id/messages?limit=` — ascending sequence.",
  });
export type ChatMessagesResponse = z.infer<typeof ChatMessagesResponseSchema>;

/** `POST /chats/:id/messages` — the stored question and its reply. */
export const ChatExchangeResponseSchema = z
  .object({
    chat: ChatSchema,
    userMessage: ChatMessageSchema,
    assistantMessage: ChatMessageSchema,
  })
  .meta({
    id: "ChatExchangeResponse",
    description:
      "`POST /chats/:id/messages` — the stored question and its reply.",
  });
export type ChatExchangeResponse = z.infer<typeof ChatExchangeResponseSchema>;

/** `POST /chats` */
export const CreateChatBodySchema = z
  .object({ title: optionalText("An optional title for the chat.") })
  .meta({ id: "CreateChatBody", description: "`POST /chats`" });
export type CreateChatBody = z.infer<typeof CreateChatBodySchema>;

/** `POST /chats/:id/messages` */
export const SendMessageBodySchema = z
  .object({
    message: z
      .string()
      .trim()
      .min(1, "must be non-blank")
      .describe("The question, answered from the caller's eligible follows."),
    aboutEpisodeId: Id.nullish().describe(
      "Scope this one question to a single episode. It narrows and never widens: the episode's channel must be one the caller follows, or the reply says so rather than answering across everything.",
    ),
  })
  .meta({ id: "SendMessageBody", description: "`POST /chats/:id/messages`" });
export type SendMessageBody = z.infer<typeof SendMessageBodySchema>;

export const PreferencesSchema = z
  .object({
    systemRules: z
      .string()
      .describe(
        "Rules applied to chat answers only, never to shared summaries.",
      ),
    updatedAt: UnixMs.nullable().describe("Null until first saved."),
  })
  .meta({ id: "Preferences", description: "The caller's chat preferences." });
export type Preferences = z.infer<typeof PreferencesSchema>;

/** `GET /preferences`, `PUT /preferences` */
export const PreferencesResponseSchema = z
  .object({ preferences: PreferencesSchema })
  .meta({
    id: "PreferencesResponse",
    description: "`GET /preferences`, `PUT /preferences`",
  });
export type PreferencesResponse = z.infer<typeof PreferencesResponseSchema>;

/** `PUT /preferences` */
export const UpdatePreferencesBodySchema = z
  .object({
    systemRules: z.string().trim().describe("Trimmed; empty clears the rules."),
  })
  .meta({ id: "UpdatePreferencesBody", description: "`PUT /preferences`" });
export type UpdatePreferencesBody = z.infer<typeof UpdatePreferencesBodySchema>;

// --- query and path parameters (API only; documented and validated from the same schema) ------------

/** `?scope=` — absent for the browsable catalog, exactly `all` for every status. */
export const ScopeQuerySchema = z.object({
  scope: z
    .enum(["all"])
    .describe(
      "`all` widens the collection to everything the system holds, declined channels included.",
    )
    .optional(),
});
export type ScopeQuery = z.infer<typeof ScopeQuerySchema>;

/** `?channelId=` — whatever was pasted: a bare `UC…` id or a URL containing `/channel/UC…`. */
export const ChannelFeedQuerySchema = z.object({
  channelId: z
    .string()
    .trim()
    .min(1)
    .describe("A `UC…` id, or a URL containing `/channel/UC…`."),
});
export type ChannelFeedQuery = z.infer<typeof ChannelFeedQuerySchema>;

/** `?limit=` — a positive integer; the default and the ceiling belong to the callee. */
export const LimitQuerySchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .positive()
    .describe("Maximum items to return, newest first.")
    .optional(),
});
export type LimitQuery = z.infer<typeof LimitQuerySchema>;

/** An ISO 8601 instant, as every bound the digest takes. The API never takes a timezone. */
const isoInstant = (description: string) =>
  z
    .string()
    .refine(
      (value) => !Number.isNaN(Date.parse(value)),
      "must be an ISO 8601 timestamp",
    )
    .describe(description)
    .optional();

/**
 * `GET /digest` — the range query behind Queue, History and the calendar (docs/PRD.md §4.4). There
 * is no default window and no clamp: the client works out its own local day boundaries and asks for
 * the range it wants. `channelId` repeats.
 */
export const DigestQuerySchema = z.object({
  from: isoInstant(
    "Start of the range, inclusive. Omitted means no lower bound.",
  ),
  to: isoInstant("End of the range, exclusive. Omitted means no upper bound."),
  unread: z
    .stringbool()
    .describe(
      "`true` for the queue: only summaries the caller has no read receipt for. Omitted means both, which is History.",
    )
    .optional(),
  channelId: z
    .union([Id, z.array(Id)])
    .transform((value) => (Array.isArray(value) ? value : [value]))
    .describe(
      "Repeatable. Narrows the range to these channels; ids the caller is not eligible for simply match nothing.",
    )
    .optional(),
  cursor: z
    .string()
    .min(1)
    .describe("A `nextCursor` from an earlier page. Opaque; never composed.")
    .optional(),
  limit: z.coerce
    .number()
    .int()
    .positive()
    .max(200)
    .describe("Rows per page. Default 50, maximum 200.")
    .optional(),
  compact: z
    .stringbool()
    .describe(
      "`true` answers rows rather than episodes: no summary bodies and no related items.",
    )
    .optional(),
});
export type DigestQuery = z.infer<typeof DigestQuerySchema>;

/** `/channels/:id` and its sub-resources. Format is checked by the Registry (400 when malformed). */
export const ChannelParamsSchema = z.object({
  id: Id.describe("Canonical `UC…` channel id."),
});
export type ChannelParams = z.infer<typeof ChannelParamsSchema>;

/** `/episodes/:episodeId` — an episode names itself; its id is unique across the catalog. */
export const EpisodeIdParamsSchema = z.object({
  episodeId: Id.describe(
    "The episode id: the YouTube video id it was discovered as.",
  ),
});
export type EpisodeIdParams = z.infer<typeof EpisodeIdParamsSchema>;

/** `/channels/:id/episodes/:episodeId/retry|skip`. */
export const EpisodeParamsSchema = z.object({
  id: Id.describe("Canonical `UC…` channel id."),
  episodeId: Id.describe(
    "The episode id: the YouTube video id it was discovered as.",
  ),
});
export type EpisodeParams = z.infer<typeof EpisodeParamsSchema>;

/** `/follows/:channelId`. */
export const FollowParamsSchema = z.object({
  channelId: Id.describe("Canonical `UC…` channel id."),
});
export type FollowParams = z.infer<typeof FollowParamsSchema>;

/** `/chats/:id/messages` (M4). */
export const ChatParamsSchema = z.object({
  id: Id.describe("Chat id."),
});
export type ChatParams = z.infer<typeof ChatParamsSchema>;
